default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: landetech
  host: db
  port: 5432
  pool: 5
  
development:
  <<: *default
  database: landetech_development

test:
  <<: *default
  database: landetech_test

production:
  <<: *default
  database: landetech_production